-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES 
FROM BOOK B, AUTHOR A, BOOK_SALES BS
WHERE B.BOOK_ID = BS.BOOK_ID
AND A.AUTHOR_ID = B.AUTHOR_ID
AND TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, CATEGORY, AUTHOR_NAME
ORDER BY A.AUTHOR_ID, CATEGORY DESC