-- 코드를 입력하세요
 
SELECT PRODUCT_CODE, (SUM(A.SALES_AMOUNT) * B.PRICE) AS SALES
FROM OFFLINE_SALE AS A
LEFT JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;