-- 코드를 입력하세요
SELECT CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * 30 * (1 - B.discount_rate / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단','SUV')
 AND CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
 AND DURATION_TYPE = '30일 이상'
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC