SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact_%'
    AND (SEX_UPON_OUTCOME LIKE 'Spayed_%' 
        OR SEX_UPON_OUTCOME LIKE 'Neutered_%')  
ORDER BY A.ANIMAL_ID