-- 코드를 입력하세요
SELECT A.CAR_ID, NVL(AVAILABILITY, '대여 가능') AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A
LEFT JOIN (
    SELECT CAR_ID, '대여중' AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE) B
ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC

