SELECT B.PRODUCT_ID, A.PRODUCT_NAME, SUM(B.AMOUNT) * A.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
LEFT JOIN FOOD_ORDER AS B ON B.PRODUCT_ID = A.PRODUCT_ID
WHERE DATE_FORMAT(B.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;