-- 코드를 입력하세요
SELECT A.HOUR, NVL(B.COUNT, 0) COUNT
FROM  
(SELECT  LEVEL - 1 AS HOUR  FROM    DUAL  CONNECT BY LEVEL <= 24 ) A 
LEFT OUTER JOIN 
(SELECT TO_NUMBER(TO_CHAR(DATETIME,'hh24')) HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS 
GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'hh24'))) B
ON A.HOUR = B.HOUR
ORDER BY 1 ASC

