-- 코드를 입력하세요
SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM (SELECT CATEGORY
        , PRICE
        , PRODUCT_NAME
        , RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) RANK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유'))
WHERE RANK = 1
ORDER BY MAX_PRICE DESC